version: "3.8"

services:
  db:
    image: "postgres:15.1-alpine3.17"
    ports:
      - "3123:5432"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - "db-data:/var/lib/postgresql/data"
    environment:
      - "POSTGRES_DB=serial"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=Abc@123abc"

volumes:
  db-data:
